spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mashibing
    username: root
    password: root
  redis:
    cluster:
      nodes: 192.168.93.10:7001,192.168.93.10:7002,192.168.93.10:7003,192.168.93.10:7004,192.168.93.10:7005,192.168.93.10:7006





mybatis:
  type-aliases-package: com.msb.pojo
  mapper-locations: classpath:com/msb/mapper/*.xml
